import turtle
turtle.showturtle()
turtle.penup()
turtle.goto(60,0)
turtle.pendown ()
turtle.begin_fill()
turtle.circle(60)
turtle.color ('red')
turtle.circle(60)
turtle.end_fill ()
turtle.penup()
turtle.goto(-60,0)
turtle.pendown()
turtle.begin_fill ()
turtle.circle (60)
turtle.end_fill()
turtle.penup()
turtle.goto (0,-120)
turtle.goto(0,-60)
turtle.circle(120,steps=4)
turtle.circle(60,steps=4)
turtle.pendown()
turtle.circle(60,steps=4)
turtle.goto (0,-70)
turtle.circle (70,steps=4)
turtle.goto(0,-80)
turtle.circle(80,steps=4)
turtle.goto (0,-90)
turtle.begin_fill ()
turtle.color('white')
turtle.goto (0,-80)
turtle.goto (0,60)
turtle.color('red')
turtle.penup()
turtle.goto(0,-80)
turtle.right (45)
turtle.left (90)
turtle.forward (120)
turtle.pendown()
turtle.forward (20)
turtle.goto(0,-80)
turtle.right (45)
turtle.circle (80,steps=4)
turtle.end_fill ()
turtle.goto (0,60)
turtle.goto(0,-80)
turtle.left (135)
turtle.forward (140)
turtle.right(180)
turtle.forward(40)
turtle.begin_fill ()
turtle.circle(50,steps=4)
turtle.end_fill ()
turtle.begin_fill ()
turtle.left(45)
turtle.circle (40,steps=4)
turtle.end_fill()
turtle.goto (0,-80)
turtle.left (45)
turtle.forward (120)
turtle.forward(-20)
turtle.begin_fill()
turtle.circle (40,steps=4)
turtle.end_fill ()
turtle.right (45)
turtle.begin_fill ()
turtle.circle (40,steps=4)
turtle.end_fill ()
turtle.done ()
